Update the steps to create an azure service principal
pivotal-cf/docs-ops-manager pull request #371
Opened 2024-06-10 16:58 UTC by nader-ziada

adjust the instructions based on changes in the az cli now using `az ad sp create-for-rbac` instead of `sp create`

[#184740139]

2024-06-10 17:23 UTC, anita-flegg commented
@nader-ziada , Does this apply to both 3.0 and 2.10 or is this a draft PR for the upcoming release?
(Or maybe it really is just for 3.0 :)

2024-06-11 17:03 UTC, nader-ziada commented
it applies for both but I created another one for 2.10, let me know if that is not needed. Thanks

2024-06-11 18:21 UTC, anita-flegg requested changes
Please ensure that the Step numbering in the level headings (##) are still sequential.
It looks like you have deleted Step 4 without updating the rest of the Step umber headings.

2024-06-11 21:17 UTC, nader-ziada commented on azure/prepare-azure-terraform.html.md.erb
> -## <a id='create-credential'></a> Step 4: Create a credential for the ADD app
fixes the numbers of the following steps

2024-06-12 16:29 UTC, merged